version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: ghcr.io/framer/helmfile:latest
          update-description: true
          docker-password: $CR_PAT_PUBLISHER
          docker-username: motifus
          registry: ghcr.io
          context: "GitHub Container Registry"
          filters:
            branches:
              only:
                - circleci
