version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  publish-image:
    jobs:
      - docker/publish:
          image: framer/helmfile
          tag: latest
          docker-password: CR_PAT_PUBLISHER
          docker-username: GHCR_USER
          registry: ghcr.io
          remote-docker-dlc: true
          context: "GitHub Container Registry"
          filters:
            branches:
              only:
                - circleci
